# Generated by Django 4.1 on 2022-10-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsinsToTrack',
            fields=[
                ('asin_id', models.AutoField(primary_key=True, serialize=False)),
                ('asin', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('tracking_active', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asins_to_track',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StockRecords',
            fields=[
                ('stock_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('asin_fk', models.CharField(db_column='asin', max_length=100)),
                ('stock_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('asin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.asinstotrack')),
            ],
            options={
                'db_table': 'stock_records',
                'managed': True,
            },
        ),
    ]
